---
title: "Outsiders"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Outsiders}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width=7,
  fig.height=5,
  comment = "#>"
)
```

```{r, include = FALSE}
library(Repeatr)
```

## Introduction

A list of shows that are not presently available from the Fugazi Live Series site but are available elsewhere.  

## Fugazi Live Series Shows

[FLS0069, Juz Nagold, Nagold, Germany, 1988-11-04](https://www.youtube.com/watch?v=h-0J7Djzplo&list=PLXzdYKOUH6xj_x0Uz273TSbqMFrG80fBn&index=8&pp=iAQB)<br>
[FLS0070, Bootleg Club, Augsburg, Germany, 1988-11-05](https://archive.org/details/fugazi1988-11-05)<br>
[FLS0081, Le Gibus, Paris, France, 22-11-1988](https://www.youtube.com/watch?v=PZY_e16_XN4&list=PLXzdYKOUH6xj_x0Uz273TSbqMFrG80fBn&index=10)<br>
[FLS0107, American Legion Hall, Gainesville, FL, USA, 1989-05-06](https://www.youtube.com/watch?v=vhBFLGz6dvU&list=PLXzdYKOUH6xj_x0Uz273TSbqMFrG80fBn&index=18&pp=iAQB)<br>
[FLS0119, Radial Social Hall, Omaha, NE, USA, 1989-06-03 (part 1)](https://www.youtube.com/watch?v=B9_hUYQ5nGc&list=PLXzdYKOUH6xj_x0Uz273TSbqMFrG80fBn&index=21&pp=iAQB)<br>
[FLS0119, Radial Social Hall, Omaha, NE, USA, 1989-06-03 (part 2)](https://www.youtube.com/watch?v=BBMO72_q82c&list=PLXzdYKOUH6xj_x0Uz273TSbqMFrG80fBn&index=22&pp=iAQB)<br>
[FLS0119, Radial Social Hall, Omaha, NE, USA, 1989-06-03 (part 3)](https://www.youtube.com/watch?v=UlP7s3dmr2c&list=PLXzdYKOUH6xj_x0Uz273TSbqMFrG80fBn&index=23&pp=iAQB)<br>
[FLS0161, McGonagles, Dublin, Ireland, 1989-11-23](https://www.youtube.com/watch?v=gwIbWL55gio&list=PLXzdYKOUH6xj_x0Uz273TSbqMFrG80fBn&index=27&pp=iAQB)<br>
[FLS0176, Forum de Grenelle, Paris, France, 1989-12-11](https://www.youtube.com/watch?v=ChUGjHfodgA&list=PLXzdYKOUH6xj_x0Uz273TSbqMFrG80fBn&index=30&pp=iAQB)<br>
[FLS0809, Sapphire Ballroom, Hobart, Tasmania, Australia, 1996-11-13](https://vimeo.com/65934803)<br>
[FLS0846, Laberinto, Santiago, Chile, 1997-08-23](https://www.youtube.com/watch?v=nsl17PjJYXU&t=297s)<br>
[FLS1053, Schlachthof, Bremen, Germany, 1999-09-17](https://www.youtube.com/watch?v=HgAJusbVqLU&list=PLXzdYKOUH6xj_x0Uz273TSbqMFrG80fBn&index=190)<br>
[FLS0970, Mission Dolores Park, San Francisco, CA, USA, 2000-06-04](https://www.youtube.com/watch?v=y7vR62XMNRo&list=PLXzdYKOUH6xj_x0Uz273TSbqMFrG80fBn&index=196&pp=iAQB)<br>
[FLS0972, Fort Reno, Washington, DC, USA, 2000-08-07 (part 1)](https://www.youtube.com/watch?v=dXX_CzyQZOE&list=PLXzdYKOUH6xj_x0Uz273TSbqMFrG80fBn&index=197)<br>
[FLS0972, Fort Reno, Washington, DC, USA, 2000-08-07 (part 2)](https://www.youtube.com/watch?v=YCniLqlEM7w&list=PLXzdYKOUH6xj_x0Uz273TSbqMFrG80fBn&index=198&pp=iAQB)<br>
[FLS1028, Holyoke War Memorial Hall, MA, USA, 2002-04-18](https://archive.org/details/Fugazi2002-04-18.AKGC1000s)<br>

## Original Fugazi Live Series Shows

[FLS22, Triple J Radio, Sydney, Australia, 1991-10-14 (availability unclear)](https://dischord.com/release/FLS22/sydney-au-oct-14-1991)

