---
title: "Playlist"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Playlist}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width=7,
  fig.height=5,
  comment = "#>"
)
```

```{r, include = FALSE}
library(Repeatr)
```

## Introduction

A list of recommended shows. I will continue to add to this list as I make my way through the live series. 

## Shows

[FLS0001, Wilson Center, Washington, DC, USA, 1987-09-03](https://www.dischord.com/fugazi_live_series/washington-dc-usa-90387)<br>
[FLS0043, 9:30 Club, Washington, DC, USA, 1988-06-15](https://www.dischord.com/fugazi_live_series/washington-dc-usa-61588)<br>
[FLS0044, Maxwell's, Hoboken, NJ, USA, 1988-06-30](https://www.dischord.com/fugazi_live_series/hoboken-nj-usa-63088)<br>
[FLS0073, Kapu, Linz, Austria 1988-10-11](https://www.dischord.com/fugazi_live_series/linz-austria-111088)<br>
[FLS0075, Centro Sociale Autogestito, Udine, Italy, 1988-11-14](https://dischord.com/fugazi_live_series/udine-italy-111488)<br>
[FLS0092, Wilson Center, Washington, DC, USA, 1988-12-29](https://dischord.com/fugazi_live_series/washington-dc-usa-122988)<br>
[FLS0095, Wilson Center, Washington, DC, USA 1989-03-24](https://www.dischord.com/fugazi_live_series/washington-dc-usa-32489)<br>
[FLS0100, Maxwell's, Hoboken, NJ, USA, 1989-04-09](https://www.dischord.com/fugazi_live_series/hoboken-nj-usa-40989)<br>
[FLS0175, Melkweg, Amsterdam, Netherlands, 1989-12-09](https://www.dischord.com/fugazi_live_series/amsterdam-netherlands-120989)<br>
[FLS0197, Pearl Street Ballroom, Northampton, MA, USA, 1990-04-14](https://www.dischord.com/fugazi_live_series/northampton-ma-usa-41490)<br>
[FLS0203, 2301 Canton Warehouse, Dallas, TX, USA, 1990-05-04](https://www.dischord.com/fugazi_live_series/dallas-tx-usa-50490)<br>
[FLS0225, Sokol Hall, Omaha, NE, USA, 1990-06-10](https://www.dischord.com/fugazi_live_series/omaha-ne-usa-61090)<br>
[FLS0230, Waukesha Expo Center, Waukesha, WI, USA, 1990-06-15](https://www.dischord.com/fugazi_live_series/waukesha-wi-usa-61590)<br>
[FLS0237, Club Soda, Kalamazoo, MI, USA, 1990-06-24](https://www.dischord.com/fugazi_live_series/kalamazoo-mi-usa-62490)<br>
[FLS0245, Troll, Hoorn, Netherlands, 1990-09-01](https://www.dischord.com/fugazi_live_series/hoorn-netherlands-90190)<br>
[FLS0252, Bierkeller, Bristol, England, 1990-09-10](https://www.dischord.com/fugazi_live_series/bristol-england-91090)<br>
[FLS0256, Riverside, Newcastle, England, 1990-09-14](https://www.dischord.com/fugazi_live_series/newcastle-england-91490)<br>
[FLS0262, King's Hall, Herne Bay, England, 1990-09-20](https://www.dischord.com/fugazi_live_series/herne-bay-england-92090)<br>
[FLS0272, Rock Lamour, Linkoping, Sweden, 1990-10-02](https://www.dischord.com/fugazi_live_series/linkoping-sweden-100290)<br>
[FLS0274, Karuzela University, Warsaw, Poland, 1990-10-05](https://www.dischord.com/fugazi_live_series/warsaw-poland-100590)<br>
[FLS0278, Glocksee, Hannover, Germany, 1990-10-09](https://www.dischord.com/fugazi_live_series/hannover-germany-100990)<br>
[FLS0287, Schlachthof, Wels, Austria, 1990-10-19](https://www.dischord.com/fugazi_live_series/wels-austria-101990)<br>
[FLS0294, Forte Prenestino, Rome, Italy, 1990-10-27](https://www.dischord.com/fugazi_live_series/rome-italy-102790)<br>
[FLS0296, Hiroshima, Torino, Italy, 1990-10-29](https://www.dischord.com/fugazi_live_series/torino-italy-102990)<br>
[FLS0303, Terminal Export, Nancy, France, 1990-11-06](https://www.dischord.com/fugazi_live_series/nancy-france-110690)<br>
[FLS0307, 9:30 Club, Washington, DC, USA, 1991-01-03](https://www.dischord.com/fugazi_live_series/washington-dc-usa-10391)<br>
[FLS0308, Lafayette Park, Washington, DC, USA, 1991-01-12](https://www.dischord.com/fugazi_live_series/washington-dc-usa-11291)<br>
[FLS0309, Sacred Heart Church, Washington, DC, USA, 1991-02-15](https://www.dischord.com/fugazi_live_series/washington-dc-usa-21591)<br>
[FLS0310, Twisters, Richmond, VA, USA, 1991-02-20](https://www.dischord.com/fugazi_live_series/richmond-va-usa-22091)<br>
[FLS0314, Marquee, New York, NY, USA, 1991-03-05](https://www.dischord.com/fugazi_live_series/new-york-ny-usa-30591)<br>
[FLS0315, Maxwell's, Hoboken, NJ, USA, 1991-03-06](https://www.dischord.com/fugazi_live_series/hoboken-nj-usa-30691)<br>
[FLS0325, Church House Inn, Providence, RI, USA, 1991-03-18](https://www.dischord.com/fugazi_live_series/providence-ri-usa-31891)<br>
[FLS0327, Sacred Heart Church Hall, Washington, DC, USA, 1991-04-12](https://www.dischord.com/fugazi_live_series/washington-dc-usa-41291)<br>
[FLS0328, Columbia University, New York, NY, USA, 1991-04-20](https://www.dischord.com/fugazi_live_series/new-york-ny-usa-42091)<br>
[FLS0330, Miracle House, Greensboro, NC, USA, 1991-05-02](https://www.dischord.com/fugazi_live_series/greensboro-nc-usa-50291)<br>
[FLS0342, Cameo Theater, Miami, FL, USA, 1991-05-16](https://www.dischord.com/fugazi_live_series/miami-fl-usa-51691)<br>
[FLS0344, Club Demolition, Gainesville, FL, USA, 1991-05-18](https://www.dischord.com/fugazi_live_series/gainesville-fl-usa-51891)<br>
[FLS0346, Tuxedo Junction, Birmingham, AL USA, 1991-05-21](https://www.dischord.com/fugazi_live_series/birmingham-al-usa-52191)<br>
[FLS0357, Mississippi Nights, St. Louis, MO, USA, 1991-06-04](https://www.dischord.com/fugazi_live_series/st-louis-mo-usa-60491)<br>
[FLS0367, Sacred Heart Church Hall, Washington, DC, USA, 1991-06-17](https://www.dischord.com/fugazi_live_series/washington-dc-usa-61791)<br>
[FLS0368, dc space, Washington, DC, USA, 1991-07-28](https://www.dischord.com/fugazi_live_series/washington-dc-usa-72891)<br>
[FLS0384, North Vancouver Sports Arena Hockey Rink, Vancouver, BC, Canada, 1991-08-19](https://www.dischord.com/fugazi_live_series/vancouver-bc-canada-81991)<br>
[FLS0389, Scottish Rites Temple, Oakland, CA, USA, 1991-08-31](https://www.dischord.com/fugazi_live_series/oakland-ca-usa-83191)<br>
[FLS0390, Gilman Street, Berkeley, CA, USA, 1991-09-01](https://www.dischord.com/fugazi_live_series/berkeley-ca-usa-90191)<br>
[FLS0396, Silver Dollar, Phoenix, AZ, USA, 1991-09-09](https://www.dischord.com/fugazi_live_series/phoenix-az-usa-90991)<br>
[FLS0412, Powerstation, Auckland, New Zealand, 1991-11-08](https://www.dischord.com/fugazi_live_series/auckland-new-zealand-110891)<br>
[FLS0414, Anti Knock, Tokyo, Japan, 1991-11-12](https://www.dischord.com/fugazi_live_series/tokyo-japan-111291)<br>
[FLS0417, dc space, Washington, DC, USA, 1991-12-08](https://www.dischord.com/fugazi_live_series/washington-dc-usa-120891)<br>
[FLS0418, Hollywood Palladium, Los Angeles, CA, USA, 1992-01-24](https://www.dischord.com/fugazi_live_series/los-angeles-ca-usa-12492)<br>
[FLS0419, Hollywood Palladium, Los Angeles, CA, USA, 1992-01-25](https://www.dischord.com/fugazi_live_series/los-angeles-ca-usa-12592)<br>
[FLS0420, St. Stephen's Church Hall, Washington, DC, USA, 1992-03-06](https://www.dischord.com/fugazi_live_series/washington-dc-usa-30692)<br>
[FLS0430, Rockbar, New Haven, CT, USA, 1992-04-13](https://www.dischord.com/fugazi_live_series/new-haven-ct-usa-41392)<br>
[FLS0438, Brixton Academy, London, England, 1992-05-09](https://www.dischord.com/fugazi_live_series/london-england-50992)<br>
[FLS0445, Vera, Gronigen, Netherlands, 1992-05-20](https://www.dischord.com/fugazi_live_series/groningen-netherlands-52092)<br>
[FLS0450, Boterhalle, Diksmuiden, Belgium, 1992-05-26](https://www.dischord.com/fugazi_live_series/diksmuide-belgium-52692)<br>
[FLS0457, En Bruto, Zaragoza, Spain, 1992-06-03](https://www.dischord.com/fugazi_live_series/zaragoza-spain-60392)<br>
[FLS0458, Murazzi, Torino, Italy, 1992-06-05](https://www.dischord.com/fugazi_live_series/torino-italy-60592)<br>
[FLS0465, Roxy, Prague, Czechoslovakia, 1992-06-13](https://www.dischord.com/fugazi_live_series/prague-czechoslovakia-61392)<br>
[FLS0468, Theaterfabrik, Munich, Germany, 1992-06-16](https://www.dischord.com/fugazi_live_series/munich-germany-61692)<br>
[FLS0469, Transmitter Festival, Hohenems, Austria, 1992-06-17](https://www.dischord.com/fugazi_live_series/hohenems-austria-61792)<br>
[FLS0471, Hugenotten Halle, Frankfurt, Germany, 1992-06-19](https://www.dischord.com/fugazi_live_series/frankfurt-germany-61992)<br>
[FLS0473, Komm, Nuremberg, Germany, 1992-06-22](https://www.dischord.com/fugazi_live_series/nuremberg-germany-62292)<br>
[FLS0472, Stadthalle Langenau, Ulm, Germany, 1992-06-20](https://www.dischord.com/fugazi_live_series/ulm-germany-62092)<br>
[FLS0478, Tempodrom, Berlin, Germany, 1992-06-28](https://www.dischord.com/fugazi_live_series/berlin-germany-62892)<br>
[FLS0483, Schlachthof, Bremen, Germany, 1992-07-03](https://www.dischord.com/fugazi_live_series/bremen-germany-70392)<br>
[FLS0484, Ungdomshuset, Copenhagen, Denmark, 1992-07-04](https://www.dischord.com/fugazi_live_series/copenhagen-denmark-70492)<br>
[FLS0487, Doornroosje, Nijmegen, Netherlands, 1992-07-11](https://www.dischord.com/fugazi_live_series/nijmegen-netherlands-71192)<br>
[FLS0488, US Capitol Plaza Supreme Court, Washington, DC, USA, 1992-07-25](https://www.dischord.com/fugazi_live_series/washington-dc-usa-72592)<br>
[FLS0489, Sanctuary Theater, Washington, DC, USA, 1992-10-23](https://www.dischord.com/fugazi_live_series/washington-dc-usa-102392)<br>
[FLS0490, Steelworkers Hall, Baltimore, MD, USA, 1992-10-25](https://www.dischord.com/fugazi_live_series/baltimore-md-usa-102592)<br>
[FLS0492, Cat's Cradle, Chapel Hill, NC, USA, 1993-02-05](https://www.dischord.com/fugazi_live_series/chapel-hill-nc-usa-20593)<br>
[FLS0501, Edge, Ft. Lauderdale, FL, USA, 1993-02-14](https://www.dischord.com/fugazi_live_series/fort-lauderdale-fl-usa-21493)<br>
[FLS0502, Ritz, Tampa, FL, USA, 1993-02-16](https://www.dischord.com/fugazi_live_series/tampa-fl-usa-21693)<br>
[FLS0505, 40 Watt, Athens, GA, USA, 1993-02-19](https://www.dischord.com/fugazi_live_series/athens-ga-usa-21993)<br>
[FLS0506, Trim Shop, Greensboro, NC, USA, 1993-02-20](https://www.dischord.com/fugazi_live_series/greensboro-nc-usa-22093)<br>
[FLS0515, New Orleans Music Hall, New Orleans, LA, USA, 1993-04-09](https://www.dischord.com/fugazi_live_series/new-orleans-la-usa-40993)<br>
[FLS0518, Liberty Lunch, Austin, TX, USA, 1993-04-12](https://www.dischord.com/fugazi_live_series/austin-tx-usa-41293)<br>
[FLS0519, Liberty Lunch, Austin, TX, USA, 1993-04-13](https://www.dischord.com/fugazi_live_series/austin-tx-usa-41393)<br>
[FLS0521, Bomb Factory, Dallas, TX, USA, 1993-04-16](https://www.dischord.com/fugazi_live_series/dallas-tx-usa-41693)<br>
[FLS0525, Coyote's, Tucson, AZ, USA, 1993-04-20](https://www.dischord.com/fugazi_live_series/tucson-az-usa-42093)<br>
[FLS0520, Showcase Special Events, San Antonio, TX, USA, 1993-04-14](https://www.dischord.com/fugazi_live_series/san-antonio-tx-usa-41493)<br>
[FLS0527, Hollywood Palladium, Los Angeles, CA, USA, 1993-04-23](https://www.dischord.com/fugazi_live_series/los-angeles-ca-usa-42393)<br>
[FLS0529, Hollywood Palladium, Los Angeles, CA, USA, 1993-04-25](https://www.dischord.com/fugazi_live_series/los-angeles-ca-usa-42593)<br>
[FLS0531, Anaconda, Santa Barbara, CA, USA, 1993-04-27](https://www.dischord.com/fugazi_live_series/santa-barbara-ca-usa-42793)<br>
[FLS0532, Veteran's Memorial Hall, Watsonville, CA, USA, 1993-04-28](https://www.dischord.com/fugazi_live_series/watsonville-ca-usa-42893)<br>
[FLS0535, Crest Theater, Sacramento, CA, USA, 1993-05-02](https://www.dischord.com/fugazi_live_series/sacramento-ca-usa-50293)<br>
[FLS0540, Capitol Theater, Olympia, WA, USA, 1993-05-08](https://www.dischord.com/fugazi_live_series/olympia-wa-usa-50893)<br>
[FLS0541, YMCA, Bellevue, WA, USA, 1993-05-09](https://www.dischord.com/fugazi_live_series/bellevue-wa-usa-50993)<br>
[FLS0544, Utah State Fairpark Coliseum, Salt Lake City, UT, USA, 1993-05-16](https://www.dischord.com/fugazi_live_series/salt-lake-city-ut-usa-51693)<br>
[FLS0550, First Avenue, Minneapolis, MN, USA, 1993-05-24](https://www.dischord.com/fugazi_live_series/minneapolis-mn-usa-52493)<br>
[FLS0552, Orpheum Theater, Green Bay, WI, USA, 1993-05-26](https://www.dischord.com/fugazi_live_series/green-bay-wi-usa-52693)<br>
[FLS0553, Oak Theatre, Chicago, IL, USA, 1993-05-28](https://www.dischord.com/fugazi_live_series/chicago-il-usa-52893)<br>
[FLS0559, Fort Reno, Washington, DC, USA, 1993-08-09](https://www.dischord.com/fugazi_live_series/washington-dc-usa-80993)<br>
[FLS0560, Maxwell's, Hoboken, NJ, USA, 1993-08-16](https://www.dischord.com/fugazi_live_series/hoboken-nj-usa-81693)<br>
[FLS0561, City Gardens, Trenton, NJ, USA, 1993-08-17](https://www.dischord.com/fugazi_live_series/trenton-nj-usa-81793)<br>
[FLS0571, Memorial Hall, Kansas City, KS, USA 1993-8-28](https://dischord.com/fugazi_live_series/kansas-city-ks-usa-82893)<br>
[FLS0573, Illinois State University Student Center Ballroom, Normal, IL, USA, 1993-09-01](https://www.dischord.com/fugazi_live_series/normal-il-usa-90193)<br>
[FLS0577, Nautica Stage, Cleveland, OH, USA, 1993-09-05](https://www.dischord.com/fugazi_live_series/cleveland-oh-usa-90593)<br>
[FLS0579, Peter Clark Hall University of Guelph, Guelph, Ontario, Canada, 1993-09-08](https://www.dischord.com/fugazi_live_series/guelph-ont-canada-90893)<br>
[FLS0584, Cook Commons, Burlington, Vermont, USA, 1993-09-13](https://www.dischord.com/fugazi_live_series/burlington-vt-usa-91393)<br>
[FLS0587, Wallace Civic Center, Fitchburg, MA, USA, 1993-09-17](https://www.dischord.com/fugazi_live_series/fitchburg-ma-usa-91793)<br>
[FLS0589, Lupo's Heartbreak Hotel, Providence, RI, USA, 1993-09-19](https://www.dischord.com/fugazi_live_series/providence-ri-usa-91993)<br>
[FLS0592, S.U.N.Y. Binghamton, Binghamton, NY, USA, 1993-09-22](https://www.dischord.com/fugazi_live_series/binghamton-ny-usa-92293)<br>
[FLS0593, Roseland Ballroom, New York, NY, USA, 1993-09-24](https://www.dischord.com/fugazi_live_series/new-york-city-ny-usa-92493)<br>
[FLS0597, Trocadero, Philadelphia, PA, USA, 1993-09-28](https://www.dischord.com/fugazi_live_series/philadelphia-pa-usa-92893)<br>
[FLS0598, Strand, Rehobeth Beach, DE, USA, 1993-09-29](https://www.dischord.com/fugazi_live_series/rehoboth-beach-de-usa-92993)<br>
[FLS0603, Club Quattro, Tokyo, Japan, 1993-11-06](https://www.dischord.com/fugazi_live_series/tokyo-japan-110693)<br>
[FLS0604, Bukit Batok Community Center, Singapore, Singapore, 1993-11-08](https://www.dischord.com/fugazi_live_series/singapore-singapore-110893)<br>
[FLS0609, Collingwood Town Hall, Melbourne, VIC, Australia, 1993-11-14](https://www.dischord.com/fugazi_live_series/melbourne-vic-australia-111493)<br>
[FLS0613, Sydney Town hall, Sydney, Australia, 1993-11-20](https://www.dischord.com/fugazi_live_series/sydney-australia-112093)<br>
[FLS0619, Windmill Hill War Memorial, Launceston, Tasmania, Australia, 1993-12-04](https://www.dischord.com/fugazi_live_series/launceston-tas-australia-120493)<br>
[FLS0621, Sammy's, Dunedin, New Zealand, 1993-12-09](https://www.dischord.com/fugazi_live_series/dunedin-new-zealand-120993)<br>
[FLS0624, Powerstation, Auckland, New Zealand, 1993-12-12](https://www.dischord.com/fugazi_live_series/auckland-new-zealand-121293)<br>
[FLS0628, Belo Horizonte Independent Music Festival, Belo Horizonte, Brazil, 1994-08-15](https://www.dischord.com/fugazi_live_series/belo-horizonte-brazil-81594)<br>
[FLS0630, Colegio Leao XIII Hall, Itaborai, Brazil, 1994-08-19](https://www.dischord.com/fugazi_live_series/itaborai-brazil-81994)<br>
[FLS0632, Aeroanta, Sao Paulo, Brazil, 1994-08-21](https://www.dischord.com/fugazi_live_series/sao-paulo-brazil-82194)<br>
[FLS0637, Long Branch Community Center, Silver Spring, MD, USA, 1994-11-20](https://www.dischord.com/fugazi_live_series/silver-spring-md-usa-112094)<br>
[FLS0638, 9:30 Club, Washington, DC, USA, 1994-11-27](https://www.dischord.com/fugazi_live_series/washington-dc-usa-112794)<br>
[FLS0639, Black Cat, Washington, DC, USA, 1994-11-29](https://www.dischord.com/fugazi_live_series/washington-dc-usa-112994)<br>
[FLS0645, Irving Plaza, New York, NY, USA, 1995-04-05](https://www.dischord.com/fugazi_live_series/new-york-city-ny-usa-40595)<br>
[FLS0653, University of Delaware Carpenter Hall, Newark, DE, USA, 1995-04-14](https://www.dischord.com/fugazi_live_series/newark-de-usa-41495)<br>
[FLS0659, Queen's Hall, Belfast, Northern Ireland, 1995-05-09](https://www.dischord.com/fugazi_live_series/belfast-northern-ireland-50995)<br>
[FLS0664, Metropolitan University, Leeds, England, 1995-05-15](https://www.dischord.com/fugazi_live_series/leeds-england-51595)<br>
[FLS0668, Le Pharos, Arras, France, 1995-05-20](https://www.dischord.com/fugazi_live_series/arras-france-52095)<br>
[FLS0671, Le Confort Moderne, Poitiers, France, 1995-05-24](https://www.dischord.com/fugazi_live_series/poitiers-france-52495)<br>
[FLS0677, Gartejo, Lisbon, Portugal, 1995-05-31](https://www.dischord.com/fugazi_live_series/lisbon-portugal-53195)<br>
[FLS0679, Zeleste, Barcelona, Spain, 1995-06-03](https://www.dischord.com/fugazi_live_series/barcelona-spain-60395)<br>
[FLS0685, Salle Des Fetes, Kingersheim, France, 1995-06-10](https://www.dischord.com/fugazi_live_series/kingersheim-france-61095)<br>
[FLS0688, CPA, Florence, Italy, 1995-06-14](https://www.dischord.com/fugazi_live_series/florence-italy-61495)<br>
[FLS0692, Porto Catania Outdoor Show, Ente Fiera Harbor, Catania, Italy, 1995-06-18](https://www.dischord.com/fugazi_live_series/catania-sicily-italy-61895)<br>
[FLS0693, Forte Prenestino, Rome, Italy, 1995-06-20](https://www.dischord.com/fugazi_live_series/rome-italy-62095)<br>
[FLS0702, Hallschlag JZ, Stuttgart, Germany, 1995-06-30](https://www.dischord.com/fugazi_live_series/stuttgart-germany-63095)<br>
[FLS0704, TU Mensa, Berlin, Germany, 1995-07-02](https://www.dischord.com/fugazi_live_series/berlin-germany-70295)<br>
[FLS0706, Fabrik, Hamburg, Germany, 1995-07-04](https://www.dischord.com/fugazi_live_series/hamburg-germany-70495)<br>
[FLS0711, Rockmaskinen, Copenhagen, Denmark, 1995-07-10](https://www.dischord.com/fugazi_live_series/copenhagen-denmark-71095)<br>
[FLS0719, Carleton University Porter Hall, Ottawa, Ontario, Canada, 1995-09-26](https://www.dischord.com/fugazi_live_series/ottawa-on-canada-92695)<br>
[FLS0725, Newport, Columbus, OH, USA, 1995-10-03](https://www.dischord.com/fugazi_live_series/columbus-oh-usa-100395)<br>
[FLS0727, Bogart's, Cincinnati, OH, USA, 1995-10-05](https://www.dischord.com/fugazi_live_series/cincinnati-oh-usa-100595)<br>
[FLS0730, Mississippi Nights, St. Louis, MO, USA, 1995-10-08](https://www.dischord.com/fugazi_live_series/st-louis-mo-usa-100895)<br>
[FLS0731, Expo Gardens, Peoria, IL, USA, 1995-10-09](https://www.dischord.com/fugazi_live_series/peoria-il-usa-100995)<br>
[FLS0732, Rainbo Roller Rink, Chicago, IL, USA, 1995-10-10](https://www.dischord.com/fugazi_live_series/chicago-il-usa-101095)<br>
[FLS0736, First Avenue, Minneapolis, MN, USA, 1995-10-15](https://www.dischord.com/fugazi_live_series/minneapolis-mn-usa-101595)<br>
[FLS0746, Capitol Theater, Olympia, WA, USA, 1995-10-29](https://www.dischord.com/fugazi_live_series/olympia-wa-usa-102995)<br>
[FLS0755, Soma, San Diego, CA, USA, 1995-11-10](https://www.dischord.com/fugazi_live_series/san-diego-ca-usa-111095)<br>
[FLS0759, Liberty Lunch, Austin, TX, USA, 1995-11-16](https://www.dischord.com/fugazi_live_series/austin-tx-usa-111695)<br>
[FLS0761, Showcase Special Events, San Antonio, TX, USA, 1995-11-18](https://www.dischord.com/fugazi_live_series/san-antonio-tx-usa-111895)<br>
[FLS0764, Black Cat, Washington, DC, USA, 1996-01-30](https://www.dischord.com/fugazi_live_series/washington-dc-usa-13096)<br>
[FLS0765, 9:30 Club, Washington, DC, USA, 1996-01-31](https://www.dischord.com/fugazi_live_series/washington-dc-usa-13196)<br>
[FLS0772, 40 Watt, Athens, GA, USA, 1996-03-26](https://www.dischord.com/fugazi_live_series/athens-ga-usa-32696)<br>
[FLS0773, University of Alabama Spragins Hall Gym, Huntsville, AL, USA, 1996-03-27](https://www.dischord.com/fugazi_live_series/huntsville-al-usa-32796)<br>
[FLS0775, Masquerade, Atlanta, GA, USA, 1996-03-29](https://www.dischord.com/fugazi_live_series/atlanta-ga-usa-32996)<br>
[FLS0781, Tipitina's, New Orleans, LA, USA, 1996-04-05](https://www.dischord.com/fugazi_live_series/new-orleans-la-usa-40596)<br>
[FLS0783, D&I Colonial Hall, Houston, TX, USA, 1996-04-08](https://www.dischord.com/fugazi_live_series/houston-tx-usa-40896)<br>
[FLS0789, First Baptist Church, Washington, DC, USA, 1996-04-19](https://www.dischord.com/fugazi_live_series/washington-dc-usa-41996)<br>
[FLS1051, Fort Reno, Washington, DC, USA 1996-08-15](https://www.dischord.com/fugazi_live_series/washington-dc-081596)<br>
[FLS0790, Malcolm X Park, Washington, DC, 1996-09-29](https://www.dischord.com/fugazi_live_series/washington-dc-usa-92996)<br>
[FLS0791, Groove, Honolulu, HI, USA, 1996-10-16](https://www.dischord.com/fugazi_live_series/honolulu-hi-usa-101696)<br>
[FLS0795, Pepperland, Okayama, Japan, 1996-10-22](https://www.dischord.com/fugazi_live_series/okayama-japan-102296)<br>
[FLS0798, Guilty, Tokyo, Japan, 1996-10-26](https://www.dischord.com/fugazi_live_series/tokyo-japan-102696)<br>
[FLS0800, Guilty, Tokyo, Japan, 1996-10-28](https://www.dischord.com/fugazi_live_series/tokyo-japan-102896)<br>
[FLS0808, Adelaide University, Adelaide, Australia, 1996-11-12](https://www.dischord.com/fugazi_live_series/adelaide-australia-111296)<br>
[FLS0809, Sapphire Ballroom, Hobart, Tasmania, Australia, 1996-11-13](https://www.dischord.com/fugazi_live_series/hobart-tz-australia-111396)<br>
[FLS0814, NYU Loeb Center, New York, NY, USA, 1997-05-02](https://www.dischord.com/fugazi_live_series/new-york-city-ny-usa-50297)<br>
[FLS0815, Electric Factory, Philadelphia, PA, USA, 1997-05-03](https://www.dischord.com/fugazi_live_series/philadelphia-pa-usa-50397)<br>
[FLS0821, Metro Theatre, Sydney, Australia, 1997-06-15](https://www.dischord.com/fugazi_live_series/sydney-australia-61597)<br>
[FLS0823, Lava Lounge, Melbourne, Australia, 1997-06-18](https://www.dischord.com/fugazi_live_series/melbourne-australia-61897)<br>
[FLS0825, Courthouse, Geelong, Australia, 1997-06-20](https://www.dischord.com/fugazi_live_series/geelong-australia-62097)<br>
[FLS0831, Nelson Arts Centre, Nelson, New Zealand, 1997-06-29](https://www.dischord.com/fugazi_live_series/nelson-new-zealand-62997)<br>
[FLS0832, Room, Dunedin, New Zealand, 1997-07-01](https://www.dischord.com/fugazi_live_series/dunedin-new-zealand-70197)<br>
[FLS0835, Broadway, São Paulo, Brazil,  1997-08-06](https://www.dischord.com/fugazi_live_series/sao-paulo-brazil-80697)<br>
[FLS0840, 92 Graus, Curitiba, Brazil, 1997-08-14](https://www.dischord.com/fugazi_live_series/curitiba-brazil-81497)<br>
[FLS0842, Trash, Belo Horizonte, Brazil, 1997-08-16](https://www.dischord.com/fugazi_live_series/belo-horizonte-brazil-81697)<br>
[FLS0844, Bar do 3, Santos, Brazil, 1997-08-20](https://www.dischord.com/fugazi_live_series/santos-brazil-82097)<br>
[FLS0847, Fort Reno, Washington, DC, USA, 1997-08-29](https://www.dischord.com/fugazi_live_series/washington-dc-usa-82997)<br>
[FLS0848, Wilson Center, Washington, DC, USA, 1997-09-03](https://www.dischord.com/fugazi_live_series/washington-dc-usa-90397)<br>
[FLS0849, 180 Club, Hagerstown, MD, USA, 1998-05-01](https://www.dischord.com/fugazi_live_series/hagerstown-md-usa-50198)<br>
[FLS0851, Newport, Columbus, OH, USA, 1998-05-03](https://www.dischord.com/fugazi_live_series/columbus-oh-usa-50398)<br>
[FLS0853, Agora Theater, Cleveland, OH, USA, 1998-05-05](https://www.dischord.com/fugazi_live_series/cleveland-oh-usa-50598)<br>
[FLS0854, Bogart's, Cincinnati, OH, USA, 1998-05-06](https://www.dischord.com/fugazi_live_series/cincinnati-oh-usa-50698)<br>
[FLS0857, State Theater, Detroit, MI, USA, 1998-05-09](https://www.dischord.com/fugazi_live_series/detroit-mi-usa-50998)<br>
[FLS0859, Teamsters Hall, Baltimore, MD, USA, 1998-05-12](https://www.dischord.com/fugazi_live_series/baltimore-md-usa-51298)<br>
[FLS0863, Phoenix Theater, Toronto, ON, Canada, 1998-07-19](https://www.dischord.com/fugazi_live_series/toronto-on-canada-71998)<br>
[FLS0870, Maxwell's, Hoboken, NJ, USA, 1998-07-27](https://www.dischord.com/fugazi_live_series/hoboken-nj-usa-72798)<br>
[FLS0872, Sanctuary Theater, Washington, DC, USA, 1998-07-31](https://www.dischord.com/fugazi_live_series/washington-dc-usa-73198)<br>
[FLS0875, First Avenue, Minneapolis, MN, USA, 1998-11-15](https://www.dischord.com/fugazi_live_series/minneapolis-mn-usa-111598)<br>
[FLS0877, Sokol Hall, Omaha, NE, USA, 1998-11-17](https://www.dischord.com/fugazi_live_series/omaha-ne-usa-111798)<br>
[FLS0880, Fitzgerald's, Houston, TX, USA, 1998-11-21](https://www.dischord.com/fugazi_live_series/houston-tx-usa-112198)<br>
[FLS0881, Liberty Lunch, Austin, TX, USA, 1998-11-22](https://www.dischord.com/fugazi_live_series/austin-tx-usa-112298)<br>
[FLS0889, Sanctuary Theater, Washington, DC, USA, 1998-12-03](https://dischord.com/fugazi_live_series/washington-dc-usa-120398)<br>
[FLS0890, George Mason University Johnson Center, Fairfax, VA, USA, 1998-12-04](https://dischord.com/fugazi_live_series/fairfax-va-usa-120498)<br>
[FLS0891, Soma, San Diego, CA, USA, 1999-02-18](https://dischord.com/fugazi_live_series/san-diego-ca-usa-21899)<br>
[FLS0893, Veteran's Memorial Hall, Watsonville, CA, USA, 1999-02-20](https://dischord.com/fugazi_live_series/watsonville-ca-usa-22099)<br>
[FLS0895, Maritime, San Francisco, CA, USA, 1999-02-22](https://dischord.com/fugazi_live_series/san-francisco-ca-usa-22299)<br>
[FLS0897, Crest Theater, Sacramento, CA, USA, 1999-02-24](https://dischord.com/fugazi_live_series/sacramento-ca-usa-22499)<br>
[FLS0898, Crystal Ballroom, Portland, OR, USA, 1999-02-26](https://dischord.com/fugazi_live_series/portland-or-usa-22699)<br>
[FLS0900, DV8, Seattle, WA, USA, 1999-02-28](https://dischord.com/fugazi_live_series/seattle-wa-usa-22899)<br>
[FLS0903, Juarez Hall, Bakersfield, CA, USA, 1999-03-04](https://dischord.com/fugazi_live_series/bakersfield-ca-usa-30499)<br>
[FLS0907, Palace, Los Angeles, CA, USA, 1999-03-09](https://dischord.com/fugazi_live_series/los-angeles-ca-usa-30999)<br>
[FLS0909, National Radio Building, Reykjavik, Iceland, 1999-04-27](https://dischord.com/fugazi_live_series/reykjavik-iceland-42799)<br>
[FLS0912, Riverside, Newcastle, England, 1999-05-02](https://dischord.com/fugazi_live_series/newcastle-england-50299)<br>
[FLS0918, Temple Bar Music Center, Dublin, Ireland, 1999-05-09](https://dischord.com/fugazi_live_series/dublin-ireland-50999)<br>
[FLS0922, Brighton Centre, Brighton, England, 1999-05-14](https://dischord.com/fugazi_live_series/brighton-england-51499)<br>
[FLS0923, Rex, London, England, 1999-05-15](https://dischord.com/fugazi_live_series/london-england-51599)<br>
[FLS0924, Fort Reno, Washington, DC, USA, 1999-08-26](https://dischord.com/fugazi_live_series/washington-dc-usa-82699)<br>
[FLS0926, Fabrik, Hamburg, Germany, 1999-09-18](https://dischord.com/fugazi_live_series/hamburg-germany-91899)<br>
[FLS0938, CPA, Florence, Italy, 1999-10-01](https://dischord.com/fugazi_live_series/florence-italy-100199)<br>
[FLS0941, Rote Fabrik, Zurich, Switzerland, 1999-10-05](https://dischord.com/fugazi_live_series/zurich-switzerland-100599)<br>
[FLS0942, L'Usine, Geneva, Switzerland, 1999-10-06](https://dischord.com/fugazi_live_series/geneva-switzerland-100699)<br>
[FLS0943, Theatre Du Moulin, Marseille, France, 1999-10-07](https://dischord.com/fugazi_live_series/marseille-france-100799)<br>
[FLS0948, L'Olympic, Nantes, France, 1999-10-13](https://dischord.com/fugazi_live_series/nantes-france-101399)<br>
[FLS0949, Le Cafe De la Danse, Paris, France, 1999-10-14](https://dischord.com/fugazi_live_series/paris-france-101499)<br>
[FLS0950, Ancienne Belgique, Brussels, Belgium, 1999-10-15](https://dischord.com/fugazi_live_series/brussels-belgium-101599)<br>
[FLS0954, Roxy, New York, NY, USA, 1999-12-03](https://dischord.com/fugazi_live_series/new-york-city-ny-usa-120399)<br>
[FLS0956, 9:30 Club, Washington, DC, USA, 1999-12-05](https://dischord.com/fugazi_live_series/washington-dc-usa-120599)<br>
[FLS0959, 40 Watt, Athens, GA, USA, 1999-12-18](https://dischord.com/fugazi_live_series/athens-ga-usa-121899)<br>
[FLS0963, Tremont Music Hall, Charlotte, NC, USA, 2000-01-13](https://dischord.com/fugazi_live_series/charlotte-nc-usa-11300)<br>
[FLS0969, Moon, Tallahassee, FL, USA, 2000-01-20](https://dischord.com/fugazi_live_series/tallahassee-fl-usa-12000)<br>
[FLS0972, Fort Reno, Washington, DC,  2000-08-07](https://dischord.com/fugazi_live_series/washington-dc-usa-80700)<br>
[FLS0974, Kolingsborg, Stockholm, Sweden, 2000-10-01](https://dischord.com/fugazi_live_series/stockholm-sweden-100100)<br>
[FLS0980, Mejeriet, Lund, Sweden,  2000-10-08](https://dischord.com/fugazi_live_series/lund-sweden-100800)<br>
[FLS0982, Ogden Theater, Denver, CO, USA, 2001-04-05](https://dischord.com/fugazi_live_series/denver-co-usa-40501)<br>
[FLS0983, Ogden Theater, Denver, CO, USA, 2001-04-06](https://dischord.com/fugazi_live_series/denver-co-usa-40601)<br>
[FLS0987, Rialto Theater, Tucson, AZ, USA, 2001-04-10](https://dischord.com/fugazi_live_series/tucson-az-usa-41001)<br>
[FLS0993, El Torreon, Kansas City, MO, USA 2001-04-18](https://dischord.com/fugazi_live_series/kansas-city-mo-usa-41801)<br>
[FLS0998, Sacred Heart Church, Washington, DC, USA, 2001-04-27](https://dischord.com/fugazi_live_series/washington-dc-usa-42701)<br>
[FLS1001, Congress Theater, Chicago, IL, USA, 2001-06-24](https://dischord.com/fugazi_live_series/chicago-il-usa-62401)<br>
[FLS1003, First Avenue, Minneapolis, MN, USA, 2001-06-27](https://dischord.com/fugazi_live_series/minneapolis-mn-usa-62701)<br>
[FLS1009, MacEwan Hall, Calgary, AB, Canada, 2001-07-03](https://dischord.com/fugazi_live_series/calgary-ab-canada-70301)<br>
[FLS1011, Archie Browning Centre, Victoria, BC, Canada, 2001-07-06](https://dischord.com/fugazi_live_series/victoria-bc-canada-70601)<br>
[FLS1013, Fort Reno, Washington, DC, USA, 2001-08-13](https://dischord.com/fugazi_live_series/washington-dc-usa-81301)<br>
[FLS1014, University of Richmond Greek Amphitheater, Richmond, VA, USA, 2002-03-22](https://dischord.com/fugazi_live_series/richmond-va-usa-32202)<br>
[FLS1015, Iitz, Raleigh, NC, USA, 2002-03-23](https://dischord.com/fugazi_live_series/raleigh-nc-usa-32302)<br>
