---
title: "Shows"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Shows}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width=7,
  fig.height=5,
  comment = "#>"
)
```

```{r, include = FALSE}
library(Repeatr)
```

## Introduction

This is my list of shows I plan to go back to and listen to again once I have finished my journey through the [Fugazi Live Series](https://www.dischord.com/fugazi_live_series).

## Shows

[FLS0001, Wilson Center, Washington, DC USA 1987-09-03](https://www.dischord.com/fugazi_live_series/washington-dc-usa-90387)

[FLS0044, Maxwell's, Hoboken, NJ USA 1988-06-30](https://www.dischord.com/fugazi_live_series/hoboken-nj-usa-63088)

[FLS0095, Wilson Center, Washington, DC USA 1989-03-24](https://www.dischord.com/fugazi_live_series/washington-dc-usa-32489)

[FLS0100, Maxwell's, Hoboken, NJ USA 1989-04-09](https://www.dischord.com/fugazi_live_series/hoboken-nj-usa-40989)

[FLS0203, 2301 Canton Warehouse, Dallas, TX USA 1990-05-04](https://www.dischord.com/fugazi_live_series/dallas-tx-usa-50490)

[FLS0225, Sokol Hall, Omaha, NE USA 1990-06-10](https://www.dischord.com/fugazi_live_series/omaha-ne-usa-61090)

[FLS0230, Waukesha Expo Center, Waukesha, WI USA 1990-06-15](https://www.dischord.com/fugazi_live_series/waukesha-wi-usa-61590)

[FLS0237, Club Soda, Kalamazoo, MI USA 1990-06-24](https://www.dischord.com/fugazi_live_series/kalamazoo-mi-usa-62490)

[FLS0245, Troll, Hoorn, Netherlands 1990-09-01](https://www.dischord.com/fugazi_live_series/hoorn-netherlands-90190)

[FLS0252, Bierkeller, Bristol, England 1990-09-10](https://www.dischord.com/fugazi_live_series/bristol-england-91090)

[FLS0256, Riverside, Newcastle, England 1990-09-14](https://www.dischord.com/fugazi_live_series/newcastle-england-91490)

[FLS0262, King's Hall, Herne Bay, England 1990-09-20](https://www.dischord.com/fugazi_live_series/herne-bay-england-92090)

[FLS0272, Rock Lamour, Linkoping, Sweden 1990-10-02](https://www.dischord.com/fugazi_live_series/linkoping-sweden-100290)

[FLS0278, Glocksee, Hannover, Germany 1990-10-09](https://www.dischord.com/fugazi_live_series/hannover-germany-100990)

[FLS0287, Schlachthof, Wels, Austria 1990-10-19](https://www.dischord.com/fugazi_live_series/wels-austria-101990)

[FLS0294, Forte Prenestino, Rome, Italy 1990-10-27](https://www.dischord.com/fugazi_live_series/rome-italy-102790)

[FLS0296, Hiroshima, Torino, Italy 1990-10-29](https://www.dischord.com/fugazi_live_series/torino-italy-102990)

[FLS0303, Terminal Export, Nancy, France 1990-11-06](https://www.dischord.com/fugazi_live_series/nancy-france-110690)

[FLS0307, 9:30 Club, Washington, DC, USA 1991-01-03](https://www.dischord.com/fugazi_live_series/washington-dc-usa-10391)

[FLS0308, Lafayette Park, Washington, DC, USA 1991-01-12](https://www.dischord.com/fugazi_live_series/washington-dc-usa-11291)

[FLS0309, Sacred Heart Church, Washington, DC, USA 1991-02-15](https://www.dischord.com/fugazi_live_series/washington-dc-usa-21591)

[FLS0314, Marquee, New York, NY, USA 1991-03-05](https://www.dischord.com/fugazi_live_series/new-york-ny-usa-30591)
