---
title: "Songnumberone"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Songnumberone}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, include = FALSE}
library(Repeatr)
```

## ["Song #1"](https://fugazi.bandcamp.com/track/song-1)

A look into Fugazi's choices of opening songs using metadata from the [Fugazi Live Series](https://www.dischord.com/fugazi_live_series).  

Let's get preferences data from the song number one choice model results.

```{r }
mypreferences <- results.ml.Repeatr4_fs
``` 

Now let's convert the parameter estimates to a rating scale from 0 to 1

```{r }

mymin <- min(mypreferences$Estimate)

mypreferences <- mypreferences %>%
  mutate(Estimate2 = Estimate - mymin)

mymax <- max(mypreferences$Estimate2)

mypreferences <- mypreferences %>%
  mutate(rating = Estimate2/mymax)

```   

Let's calculate performance counts and performance intensity.

```{r }
songnumberone_counts <- Repeatr2 %>%
  filter(first_song==1) %>%
  rename(songid = alt)

songnumberone_counts <- songnumberone_counts %>%
  group_by(songid) %>%
  summarise(chosen= sum(choice), available_rl=sum(available_rl)) %>%
  arrange(desc(chosen)) %>%
  ungroup()

songnumberonesummary <- mypreferences %>%
  left_join(songnumberone_counts)

songnumberonesummary <- songnumberonesummary %>%
  mutate(intensity = chosen/available_rl)

mylaunchdatelookup <- fugazi_song_performance_intensity %>%
  select(songid, launchdate)

songnumberonesummary <- songnumberonesummary %>%
  left_join(mylaunchdatelookup)

songnumberonesummary <- songnumberonesummary %>%
  select(songid, song, launchdate, chosen, available_rl, intensity, rating)

```   

Finally, let's have a look at the results.  

```{r }
knitr::kable(songnumberonesummary, "pipe")
``` 

